### ISSUE TITLE
Unable to deploy Recurrent calls scheduling contract example

### ISSUE THREAD

**Issue by Gagan0436** [ETH-Pantheon/Aion#2] opened 2018-11-06 07:26 UTC
I am using remix.ethereum.org injected with Metamask to deploy Recurrent calls example on Ropsten Network. 
Now, when I try to deploy the same, I got following error: 

GAS ESTIMATION FAILED
```
Gas estimation errored with the following message (see below). The transaction execution will likely fail. Do you want to force sending? 
JsonRpcEngine - response has no error or result for request: { "jsonrpc": "2.0", "id": 3380781411, "method": "eth_estimateGas", "params": [ { "from": "0x3b9dcea07ea000af681364189290c30941dc38f0", "data": "0x608060405234801561001057600080fd5b5060405160208061067b83398101604052516100348164010000000061003a810204565b506102c2565b60018054600160a060020a03191673fcfb45679539667f7ed55fa59a15c8cad73d9a4e1790819055604080517f6d796675636e74696f6e2875696e743235362900000000000000000000000000815281519081900360130181206024808301869052835180840390910181526044909201835260208281018051600160e060020a03167fffffffff000000000000000000000000000000000000000000000000000000009093169290921790915282517f8abdf5aa00000000000000000000000000000000000000000000000000000000815292519193600093600160a060020a039190911692638abdf5aa9260048084019391929182900301818787803b15801561014557600080fd5b505af1158015610159573d6000803e3d6000fd5b505050506040513d602081101561016f57600080fd5b5051600180546040517fdea8dc4f000000000000000000000000000000000000000000000000000000008152600a420160048201818152306024840181905260006044850181905262030d4060648601819052633b9aca006084870181905260c4870189905260e060a488019081528c5160e48901528c5165b5e620f48000909b019b50600160a060020a039098169963dea8dc4f998c99979895979496939592948e94919391929091610104019060208601908083838c5b83811015610240578181015183820152602001610228565b50505050905090810190601f16801561026d5780820380516001836020036101000a031916815260200191505b509850505050505050505060408051808303818588803b15801561029057600080fd5b505af11580156102a4573d6000803e3d6000fd5b50505050506040513d60408110156102bb57600080fd5b5050505050565b6103aa806102d16000396000f3006080604052600436106100565763ffffffff7c01000000000000000000000000000000000000000000000000000000006000350416631fe6bb64811461005857806347a5bf4f1461007057806370a221eb14610097575b005b34801561006457600080fd5b506100566004356100af565b34801561007c57600080fd5b50610085610373565b60408051918252519081900360200190f35b3480156100a357600080fd5b50610056600435610379565b6001805473ffffffffffffffffffffffffffffffffffffffff191673fcfb45679539667f7ed55fa59a15c8cad73d9a4e1790819055604080517f6d796675636e74696f6e2875696e7432353629000000000000000000000000008152815190819003601301812060248083018690528351808403909101815260449092018352602082810180517bffffffffffffffffffffffffffffffffffffffffffffffffffffffff167fffffffff000000000000000000000000000000000000000000000000000000009093169290921790915282517f8abdf5aa0000000000000000000000000000000000000000000000000000000081529251919360009373ffffffffffffffffffffffffffffffffffffffff9190911692638abdf5aa9260048084019391929182900301818787803b1580156101e957600080fd5b505af11580156101fd573d6000803e3d6000fd5b505050506040513d602081101561021357600080fd5b5051600180546040517fdea8dc4f000000000000000000000000000000000000000000000000000000008152600a420160048201818152306024840181905260006044850181905262030d4060648601819052633b9aca006084870181905260c4870189905260e060a488019081528c5160e48901528c5165b5e620f48000909b019b5073ffffffffffffffffffffffffffffffffffffffff9098169963dea8dc4f998c99979895979496939592948e94919391929091610104019060208601908083838c5b838110156102f15781810151838201526020016102d9565b50505050905090810190601f16801561031e5780820380516001836020036101000a031916815260200191505b509850505050505050505060408051808303818588803b15801561034157600080fd5b505af1158015610355573d6000803e3d6000fd5b50505050506040513d604081101561036c57600080fd5b5050505050565b60005481565b6000555600a165627a7a7230582087848b4cc0cc6e9b589e9a8a04e8ca840ea4f2c8149758023af2401f8ddc128900290000000000000000000000000000000000000000000000000000000000000014", "value": "0x0" } ] }
```
Is this code not executable?

**Comment by jfdelgad** [comment] 2018-11-06 08:17
I have fixed the example code and test it (there was a minor issue in the text). It is now functional. Be sure that you send enough ether to decontract during deployment because the first scheduling request starts during deployment (see the constructor). In Remix, you can do this by setting the field value (top right of the screen on the 'run' tab), to any value different from zero. 0.1 ether will the keep contract working for quite a while.

Let me know if you have further questions.

**Comment by ETH-Pantheon** [comment] 2018-11-06 15:40
I am closing this issue as the main problem was that ether should be provided with the deployment of the example code to pay for the scheduling fee. The code was corrected and posted again in the Readme of Aion.

**Closed by ETH-Pantheon** 2018-11-06 15:40 UTC

**Comment by Banksy-said-hi** [comment] 2021-11-26 09:34
Thanks for the explanations. I have the same error, although i provide enough ETH while deploying the sample contract. I get this message for deploying the contract: "Transaction execution failed" 

Could you please help me if you know where the problem is? I guess this might be related to the network congestion.
